# Generated by Django 5.2.7 on 2026-01-02 13:22

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alice", "0001_enable_vector_extension"),
        ("data_import", "0006_asynctask"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Descrição textual do dataset para geração de embedding",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        dimensions=768, verbose_name="Embedding Vetorial"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Informações adicionais sobre o dataset",
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "dataset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="data_import.dataimportprocess",
                        verbose_name="Dataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Embedding de Dataset",
                "verbose_name_plural": "Embeddings de Datasets",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["dataset"], name="alice_datas_dataset_fe21b0_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="alice_datas_created_cdbee1_idx"
                    ),
                ],
            },
        ),
    ]
