# Generated by Django 5.2.7 on 2026-04-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_import", "0006_asynctask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataimportprocess",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("processing", "Processando"),
                    ("active", "Ativo"),
                    ("inactive", "Inativo"),
                    ("completed", "Concluído"),
                    ("failed", "Falhou"),
                    ("archived", "Arquivado"),
                ],
                db_index=True,
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
